# Generated by Django 5.1.6 on 2025-05-15 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_changedcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconversionhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
