# Generated by Django 5.1.6 on 2025-05-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_alter_userconversionhistory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changedcurrency',
            name='old_changed_currency_rate',
        ),
    ]
